name: ChatColors
version: 1.5.3
main: org.seed419.chatcolors.ChatColors
author: SeeD419
commands:
   colors:
      description: Lists the chat color syntax
      aliases: colours
   rb:
      description: Rainbowize a message

permissions:
  chatcolors.*:
    description: Gives access to all ChatColor commands
    default: false
    children:
      chatcolors.colors: true
      chatcolors.rainbow: true
      chatcolors.format: true
  chatcolors.colors:
    description: Shows the color menu to the player
    default: false
  chatcolors.rainbow:
    description: Allows a player to rainbowize a message
    default: false
  chatcolors.format:
    description: Allows player to format their messages
    default: false
