name: ChatColors
version: 1.2
main: org.seed419.ChatColors
author: SeeD419
commands:
   colors:
      description: Lists the chat color syntax
      usage: /<command>
   rb:
      description: Rainbowize a message
      usage: /<command> <message>

